//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the MVVM Xcode Templates
//

import SwiftUI

struct ___VARIABLE_sceneName___View: View {
    @ObservedObject private var viewModel: ___VARIABLE_sceneName___ViewModel
    
    init(with viewModel: ___VARIABLE_sceneName___ViewModel) {
        self.viewModel = viewModel
    }
    
    var body: some View {
        Text("Add some view here")
    }
}

struct ___VARIABLE_sceneName___View_Previews: PreviewProvider {
    static var previews: some View {
        ___VARIABLE_sceneName___View(with: ___VARIABLE_sceneName___ViewModel(router: ___VARIABLE_sceneName___Router()))
    }
}
