//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the MVVM Xcode Templates so
//

import SwiftUI

protocol ___VARIABLE_sceneName___RouterType {
  //func routeToSomewhere() -> AnyView
}


final class ___VARIABLE_sceneName___Router: ___VARIABLE_sceneName___RouterType {

}
