//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//

import Foundation
import Combine

final class ___VARIABLE_sceneName___ViewModel: ObservableObject {

//    @Published private(set) var SomeVariable: [Any] = []
    
    var router: ___VARIABLE_sceneName___RouterType
    private var cancellables = Set<AnyCancellable>()
    
    init(router: ___VARIABLE_sceneName___RouterType) {
        self.router = router
        setUp()
    }
}

private extension ___VARIABLE_sceneName___ViewModel {
    func setUp() {
    }
}
