//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//

import Foundation
import Resolver
import Combine

final class ___VARIABLE_sceneName___ViewModel: ObservableObject {
    
   // @Injected var router: XXX type of router

    private var cancellables = Set<AnyCancellable>()
    
    init() {
        setUp()
    }
}

private extension ___VARIABLE_sceneName___ViewModel {
    func setUp() {
    }
}
