//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the MVVM Xcode Templates
//

import SwiftUI
import Resolver

struct ___VARIABLE_sceneName___View: View {
    @InjectedObject private var viewModel: ___VARIABLE_sceneName___ViewModel

    var body: some View {
        Text("Add some view here")
    }
}

struct ___VARIABLE_sceneName___View_Previews: PreviewProvider {
    static var previews: some View {
        ___VARIABLE_sceneName___View()
    }
}
